pipeline {
    agent any

    stages {
        stage('Clone Repo') {
            steps {
                git 'https://github.com/TEJASBHIDE/Practical5/edit/main/node-app'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    echo 'Building Docker image...'
                    // Navigate into the node-app directory and build
                    dir('node-app') {
                        sh 'docker build -t node-jenkins-app .'
                    }
                }
            }
        }

        stage('Stop and Remove Existing Container') {
            steps {
                script {
                    echo 'Stopping any existing container...'
                    sh '''
                    if [ $(docker ps -q -f name=node-jenkins-container) ]; then
                        docker stop node-jenkins-container
                        docker rm node-jenkins-container
                    fi
                    '''
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                script {
                    echo 'Running Docker container...'
                    sh 'docker run -d --name node-jenkins-container -p 3000:3000 node-jenkins-app'
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully.'
        }
        failure {
            echo 'Pipeline failed.'
        }
    }
}
